#!/bin/sh
 
if [ "$1" == "start" ]; then
    (
        while true; do
            if [ "$(cat /sys/class/regulator/regulator.1/state)" == "disabled" ]; then
                halt
            fi

            sleep 1
        done
    )&
fi                                          
                                   
if [ "$1" == "stop" ]; then
    echo Halt service cannot be halted 1>&2
    exit 1
fi
