#!/bin/sh
 
if [ "$1" == "start" ]; then
    modprobe usbnet                                           
    ip addr add 169.254.1.42/16 dev eth0       
    ip link set eth0 up                     
fi                                          
                                   
if [ "$1" == "stop" ]; then
    ip link set eth0 down               
    ip addr del 169.254.1.42 dev eth0   
    modprobe --remove usbnet 
fi
