#!/bin/sh

start ()
{
    cd /opt/st.hmi
    ./launch &
}

stop ()
{
    kill $(ps | grep -v sed | sed -n "s; *\([0-9]\+\) .*$(tail -n 1 /opt/st.hmi/launch);\1;p")
}
 
restart ()
{
    stop
    start
}

if [ "$1" == "start" ]; then
    start
fi

if [ "$1" == "restart" ]; then
    restart
fi                                          

if [ "$1" == "stop" ]; then
    stop
fi
